version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    rebase-strategy: "disabled"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "gradle-deps:"
    labels:
      - bot/dependabot
      - type/dependency

  - package-ecosystem: "github-actions"
    directory: "/"
    rebase-strategy: "disabled"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "gh-action:"
