[versions]
#App deps
lombok = "1.18.36"
slf4j = "2.1.0-alpha1"
jetbrains-annotation = "26.0.1"

#Test Modules
junit-jupiter = "5.11.3"

# JMH Libraries
jmh-lib = "0.9"

#Gradle Plugin
gradle-versions = "0.51.0"
jmh-pl = "0.7.3"


[libraries]
#App deps
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotation" }

#Test Modules
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
junit-platform = { module = "org.junit.platform:junit-platform-launcher" }

# JMH Libraries
jmh-core = { module = "org.openjdk.jmh:jmh-core", version.ref = "jmh-lib" }
jmh-apt = { module = "org.openjdk.jmh:jmh-generator-annprocess", version.ref = "jmh-lib" }
jmh-bytecode = { module = "org.openjdk.jmh:jmh-generator-bytecode", version.ref = "jmh-lib" }

#Gradle Plugin
gradle-versions = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "gradle-versions" }
jmh-pl = { module = "me.champeau.jmh:me.champeau.jmh.gradle.plugin", version.ref = "jmh-pl" }
