name: Build application and test


on:
  workflow_dispatch:
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches:
      - 'main'
      - 'master'
      - 'product'
      - 'prod'

      - 'develop'
      - 'dev'


env:
  JDK_VERSION: 24


jobs:
  build:
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cache
        uses: actions/cache@v5
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Setup JDK ${{ env.JDK_VERSION }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JDK_VERSION }}
          distribution: 'adopt'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Clean cache
        run: ./gradlew clean

      - name: Test
        run: ./gradlew check
